
# This creates a 10GB PV/PVC for Jenkins home to use for persistent data. The drawdown is that it uses a path on each worker nodes filesystem as storage. i
# In my lab, I'm using NFS from a secondary disk on the ansible vm and exporting it to the worker nodes so they'll all have the same data when I scale the replicas up from 1 to 3 after initial setup.
# If you're running your own DNS server, you'll need to make an A-Record for the ip given to it by MetalLB. FYI - it can be found with cmd: "kubectl get svc -n jenkins" look for a 192.168.1.x/24 address
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-crb
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: jenkins
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: jenkins
spec:
  storageClassName: nfs-ansible-server
  volumeName: mypv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # Note: This must be equal to or less than the capacity defined in your pre-existing 'mypv'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      serviceAccountName: jenkins-sa
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: mypvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
  namespace: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: jnlp
      port: 50000
      targetPort: 50000
